# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "app"
client_id = "654154eff56b8801eb5e2186aea2f0d8"
application_url = "https://link-split-pierre-scenic.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://link-split-pierre-scenic.trycloudflare.com/auth/callback",
  "https://link-split-pierre-scenic.trycloudflare.com/auth/shopify/callback",
  "https://link-split-pierre-scenic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appprojectfirst.myshopify.com"
